import Nav from "@/components/navbar/Nav";
import "../globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { NextuiProvider } from "@/provider/Nextui";
import { Inter } from 'next/font/google'
import NextTopLoader from "nextjs-toploader";


const inter = Inter({
  subsets: ['latin'],
  weight: ['500'],
  variable: '--font-inter',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${inter.variable}  font-inter `}>
        <NextIntlClientProvider messages={messages}>
          <NextuiProvider>
            <NextTopLoader
              showSpinner={false}
              easing="ease"
              speed={500}
              initialPosition={0.38}
              crawl={true}
              height={4}
            />
            <Nav locale={locale} />
            {children}
          </NextuiProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
